"""
Workflow Pydantic Schemas.
Strict data models for workflow steps, definitions, plans, and execution requests.
"""

from typing import List, Optional, Any, Dict, Union
from pydantic import BaseModel, Field, field_validator
from app.workflows.types import WorkflowStatus, StepStatus, StepType
from app.ai.schemas import StructuredRequirement


class WorkflowStep(BaseModel):
    """
    Representation of an individual workflow step in the dependency graph.
    """
    id: str = Field(..., description="Unique step identifier, e.g. 'step_1'")
    name: str = Field(..., min_length=1, description="Human-readable step name")
    type: StepType = Field(..., description="Categorized step type")
    description: str = Field(..., description="Detailed description of step action")
    order: int = Field(..., ge=1, description="Sequential display order")
    depends_on: List[str] = Field(
        default_factory=list,
        description="IDs of prerequisite steps that must finish before this step runs",
    )
    config: Dict[str, Any] = Field(
        default_factory=dict,
        description="Configuration parameters passed to the step executor",
    )
    status: StepStatus = Field(
        default=StepStatus.PENDING,
        description="Current execution status of this step",
    )
    input: Optional[Any] = Field(
        default=None,
        description="Input data payload provided to the executor",
    )
    output: Optional[Any] = Field(
        default=None,
        description="Output result generated by the executor",
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if step execution failed",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional execution metadata (durations, mock tags, etc.)",
    )

    @field_validator("id")
    @classmethod
    def validate_id(cls, v: str) -> str:
        s = v.strip()
        if not s:
            raise ValueError("Step id must not be empty.")
        return s


class WorkflowDefinition(BaseModel):
    """
    Full specification of a planned or executing workflow.
    """
    workflow_id: str = Field(..., description="Unique workflow identifier (UUID)")
    name: str = Field(..., min_length=1, description="Workflow name")
    description: str = Field(..., description="Workflow purpose summary")
    status: WorkflowStatus = Field(
        default=WorkflowStatus.PLANNED,
        description="Overall workflow lifecycle status",
    )
    input_requirement: Union[StructuredRequirement, Dict[str, Any]] = Field(
        ...,
        description="Structured requirement produced by Phase 2 or user input",
    )
    steps: List[WorkflowStep] = Field(
        ...,
        min_length=1,
        description="Ordered list of workflow steps forming the execution DAG",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Extensible workflow-level metadata",
    )
    error: Optional[str] = Field(
        default=None,
        description="Workflow-level failure message if any",
    )
    created_at: Optional[str] = Field(default=None, description="ISO timestamp of creation")
    updated_at: Optional[str] = Field(default=None, description="ISO timestamp of last update")


# API Request and Response Models

class PlanWorkflowRequest(BaseModel):
    """Payload for POST /api/v1/workflows/plan"""
    requirement: Union[StructuredRequirement, Dict[str, Any]] = Field(
        ...,
        description="Structured requirement to convert into a planned workflow",
    )
    prompt: Optional[str] = Field(
        None,
        description="Optional original natural language prompt",
    )
    workflow_id: Optional[str] = Field(
        None,
        description="Optional existing workflow ID to associate or update",
    )


class PlanWorkflowResponse(BaseModel):
    """Response payload for POST /api/v1/workflows/plan"""
    success: bool
    workflow: Optional[WorkflowDefinition] = None
    error: Optional[str] = None


class ExecuteWorkflowResponse(BaseModel):
    """Response payload for POST /api/v1/workflows/{workflow_id}/execute"""
    success: bool
    workflow: Optional[WorkflowDefinition] = None
    error: Optional[str] = None


class WorkflowStepsResponse(BaseModel):
    """Response payload for GET /api/v1/workflows/{workflow_id}/steps"""
    workflow_id: str
    status: WorkflowStatus
    steps: List[WorkflowStep]
